version: "3.8"
services:
  web:
    build:
      context: .                    # <-- repo root
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
    volumes:
      - staticfiles:/app/staticfiles

volumes:
  staticfiles:
