services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      # Force CRA to run on 3000 inside container
      - PORT=3000
      # React hot-reload polling on Windows filesystems
      - CHOKIDAR_USEPOLLING=true
